spellchecker: aspell
matrix:
- name: Markdown
  aspell:
    lang: en
  dictionary:
    wordlists:
    - .github/workflows/gibberish.txt
    - .github/workflows/names.txt
    encoding: utf-8
  pipeline:
    - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
    - pyspelling.filters.html:
        comments: true
        attributes:
        - title
        - alt
        ignores:
        - ':matches(code, pre)'
        - 'code'
        - 'pre'
  sources:
  - '*.md'
  - 'cfw-hfw-mfw/**/*.md'
  - 'big-stinky-brew/**/*.md'
  - 'welcome-to-wiki/**/*.md'
  - 'at-this-instant/**/*.md'
  - 'about-the-wiki/**/*.md'
  default_encoding: utf-8
