name: spellcheck

on:
  push:

jobs:
  spellcheck:
    name: runner / spellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out code.
      uses: actions/checkout@v2
    - name: Run PySpelling as a GitHub action
      uses: rojopolis/spellcheck-github-actions@v0.9.1