name: dontclickdontclickdontclick

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: AHHH are they broken or what?
      uses: urlstechie/urlchecker-action@master
      with:
        file_types: .md
        print_all: true
        timeout: 5
        retry_count: 3
        force_pass : true
