name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '0 0,8,16 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has not gotten much attention over the last 30 days, and will automatically be closed in 5 if it stays that way.'
          stale-pr-message: 'This PR has not gotten much attention over the last 45 days, and will automatically be closed in 10 if it stays that way.'
          close-issue-message: 'This issue was closed because nothing has been interacting with it for 5 days.'
          close-pr-message: 'This PR was closed and no changes have been commited to `Doregon:master`. If you wish to try again, create a new pull request.'
          days-before-issue-stale: 30
          days-before-pr-stale: 45
          days-before-issue-close: 5
          days-before-pr-close: 10
          stale-pr-label: 'no-pr-activity'
          stale-issue-label: 'no-issue-activity'
