name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR hasn't been interacted with in a while. If there's no activity within 10 days, it will be closed.'
          close-pr-message: 'This PR has been closed and no changes have been merged with the master branch. If you wish to merge your changes, re-open your pull request.'
          days-before-issue-stale: 30
          days-before-pr-stale: 20
          days-before-issue-close: -1
          days-before-pr-close: 10
